/**
 * What "joinable" means, measured against the boxes a real failure produced.
 *
 * Assembly writes the first epoch's initialisation segment and copies every
 * other epoch's fragments in after it. So the question a replacement epoch has
 * to answer is not "are these bytes identical" but "do these fragments decode
 * under that initialisation" — and on the real damaged title those two answers
 * differed.
 *
 * The film's own epochs carry HDR10 static metadata: `mdcv`, the mastering
 * display colour volume, and `clli`, the content light level, copied from the
 * source. A replacement generated by a colour generator has neither, and its
 * container tags differ too, so its initialisation segment came out 1046 bytes
 * against 929 — while its `hvcC` was byte-for-byte the same, because it is the
 * same encoder at the same profile, level and dimensions. Comparing whole
 * segments refused it; comparing what decoding depends on accepts it.
 */

import { describe, expect, it } from "vitest";
import {
  describeJoinMismatch,
  joinKeysMatch,
  readEpochJoinKey,
} from "./fragments";

/** Builds a minimal init segment: ftyp + moov(mvhd? no) with the boxes we read. */
function box(type: string, payload: Buffer): Buffer {
  const header = Buffer.alloc(8);
  header.writeUInt32BE(payload.length + 8, 0);
  header.write(type, 4, "latin1");
  return Buffer.concat([header, payload]);
}

function mdhd(timescale: number): Buffer {
  const payload = Buffer.alloc(24);
  payload.writeUInt32BE(0, 0); // version 0, flags
  payload.writeUInt32BE(timescale, 12);
  return box("mdhd", payload);
}

function hdlr(): Buffer {
  const payload = Buffer.alloc(24);
  payload.write("vide", 8, "latin1");
  return box("hdlr", payload);
}

function visualSampleEntry({
  format,
  width,
  height,
  children,
}: {
  format: string;
  width: number;
  height: number;
  children: Buffer[];
}): Buffer {
  const body = Buffer.alloc(78);
  body.writeUInt16BE(width, 24);
  body.writeUInt16BE(height, 26);
  return box(format, Buffer.concat([body, ...children]));
}

function initSegment({
  timescale = 24000,
  format = "hvc1",
  width = 3840,
  height = 1600,
  config = Buffer.from("decoder-configuration", "utf8"),
  extras = [] as Buffer[],
}): Buffer {
  const stsdPayload = Buffer.concat([
    Buffer.alloc(4), // version + flags
    (() => {
      const count = Buffer.alloc(4);
      count.writeUInt32BE(1, 0);
      return count;
    })(),
    visualSampleEntry({
      format,
      width,
      height,
      children: [
        box("hvcC", config),
        box("colr", Buffer.from("nclx")),
        ...extras,
      ],
    }),
  ]);
  const stbl = box("stbl", box("stsd", stsdPayload));
  const minf = box("minf", stbl);
  const mdia = box("mdia", Buffer.concat([mdhd(timescale), hdlr(), minf]));
  const trak = box("trak", mdia);
  return Buffer.concat([box("ftyp", Buffer.alloc(16)), box("moov", trak)]);
}

/** The 44 bytes of HDR10 static metadata the film has and a generator has not. */
const HDR_METADATA = [
  box("clli", Buffer.alloc(4)),
  box("mdcv", Buffer.alloc(24)),
];

describe("what has to match for epochs to join", () => {
  it("accepts a replacement that lacks only the source's HDR metadata", () => {
    const film = readEpochJoinKey(initSegment({ extras: HDR_METADATA }));
    const replacement = readEpochJoinKey(initSegment({}));
    expect(joinKeysMatch(film, replacement)).toBe(true);
    expect(describeJoinMismatch(replacement, film)).toBeUndefined();
  });

  it("refuses a different decoder configuration", () => {
    const film = readEpochJoinKey(initSegment({}));
    const other = readEpochJoinKey(
      initSegment({ config: Buffer.from("a different SPS", "utf8") }),
    );
    expect(joinKeysMatch(film, other)).toBe(false);
    expect(describeJoinMismatch(other, film)).toMatch(
      /different decoder configuration/,
    );
  });

  it("refuses a different timescale", () => {
    const film = readEpochJoinKey(initSegment({}));
    const other = readEpochJoinKey(initSegment({ timescale: 90000 }));
    expect(joinKeysMatch(film, other)).toBe(false);
    expect(describeJoinMismatch(other, film)).toMatch(/90000 media timescale/);
  });

  it("refuses different encoded dimensions", () => {
    const film = readEpochJoinKey(initSegment({}));
    const other = readEpochJoinKey(initSegment({ width: 1920, height: 800 }));
    expect(joinKeysMatch(film, other)).toBe(false);
    expect(describeJoinMismatch(other, film)).toMatch(/1920x800/);
  });

  it("refuses a different sample entry format", () => {
    const film = readEpochJoinKey(initSegment({}));
    const other = readEpochJoinKey(initSegment({ format: "avc1" }));
    expect(joinKeysMatch(film, other)).toBe(false);
    expect(describeJoinMismatch(other, film)).toMatch(/avc1 sample entry/);
  });

  it("reads the timescale, format and dimensions it was given", () => {
    const key = readEpochJoinKey(initSegment({ extras: HDR_METADATA }));
    expect(key).toMatchObject({
      mediaTimescale: 24000,
      sampleFormat: "hvc1",
      width: 3840,
      height: 1600,
    });
  });

  it("refuses an initialisation segment with no sample description", () => {
    expect(() =>
      readEpochJoinKey(
        Buffer.concat([
          box("ftyp", Buffer.alloc(16)),
          box(
            "moov",
            box("trak", box("mdia", Buffer.concat([mdhd(24000), hdlr()]))),
          ),
        ]),
      ),
    ).toThrow(/no readable sample description/);
  });
});
