// Single source of truth for every flag Seyirlik can render.
//
// The flag-icons stylesheet ships ~270 rules and ~3.5 MB of SVGs, which used to
// land in the bundle and the PWA precache in full. The Vite plugin in
// vite.config.ts trims that stylesheet down to FLAG_COUNTRY_CODES, so adding a
// language here is all that is needed to keep its flag working.

export const LANGUAGE_FLAG_COUNTRY_CODES: Record<string, string> = {
  ar: "sa",
  arabic: "sa",
  ara: "sa",
  bg: "bg",
  bul: "bg",
  bulgarian: "bg",
  ca: "es-ct",
  catalan: "es-ct",
  chi: "cn",
  chinese: "cn",
  cs: "cz",
  cze: "cz",
  ces: "cz",
  czech: "cz",
  da: "dk",
  dan: "dk",
  danish: "dk",
  de: "de",
  deu: "de",
  ger: "de",
  german: "de",
  el: "gr",
  ell: "gr",
  gre: "gr",
  greek: "gr",
  en: "gb",
  eng: "gb",
  english: "gb",
  es: "es",
  spa: "es",
  spanish: "es",
  castellano: "es",
  castilian: "es",
  fa: "ir",
  fas: "ir",
  per: "ir",
  persian: "ir",
  fi: "fi",
  fin: "fi",
  finnish: "fi",
  fr: "fr",
  fra: "fr",
  fre: "fr",
  french: "fr",
  he: "il",
  heb: "il",
  hebrew: "il",
  hi: "in",
  hin: "in",
  hindi: "in",
  hr: "hr",
  hrv: "hr",
  croatian: "hr",
  hu: "hu",
  hun: "hu",
  hungarian: "hu",
  id: "id",
  ind: "id",
  indonesian: "id",
  is: "is",
  ice: "is",
  isl: "is",
  icelandic: "is",
  it: "it",
  ita: "it",
  italian: "it",
  ja: "jp",
  jpn: "jp",
  japanese: "jp",
  ko: "kr",
  kor: "kr",
  korean: "kr",
  ms: "my",
  may: "my",
  msa: "my",
  malay: "my",
  nl: "nl",
  dut: "nl",
  nld: "nl",
  dutch: "nl",
  no: "no",
  nor: "no",
  nb: "no",
  nn: "no",
  norwegian: "no",
  pl: "pl",
  pol: "pl",
  polish: "pl",
  pt: "pt",
  por: "pt",
  portuguese: "pt",
  ro: "ro",
  rum: "ro",
  ron: "ro",
  romanian: "ro",
  ru: "ru",
  rus: "ru",
  russian: "ru",
  sk: "sk",
  slo: "sk",
  slk: "sk",
  slovak: "sk",
  sl: "si",
  slv: "si",
  slovenian: "si",
  sr: "rs",
  srp: "rs",
  serbian: "rs",
  sv: "se",
  swe: "se",
  swedish: "se",
  th: "th",
  tha: "th",
  thai: "th",
  tr: "tr",
  tur: "tr",
  turkish: "tr",
  uk: "ua",
  ukr: "ua",
  ukrainian: "ua",
  ur: "pk",
  urd: "pk",
  urdu: "pk",
  vi: "vn",
  vie: "vn",
  vietnamese: "vn",
  zh: "cn",
  zho: "cn",
};

export const COUNTRY_NAME_FLAG_CODES: Record<string, string> = {
  brazil: "br",
  brazilian: "br",
  canada: "ca",
  canadian: "ca",
  china: "cn",
  france: "fr",
  germany: "de",
  japan: "jp",
  korea: "kr",
  mexico: "mx",
  mexican: "mx",
  portugal: "pt",
  spain: "es",
  turkey: "tr",
  turkiye: "tr",
  uk: "gb",
  us: "us",
  usa: "us",
};

// Flags rendered by UI chrome rather than by media metadata, so they are not
// reachable through either lookup table above. "xx" is flag-icons' own unknown
// flag placeholder, kept so a code that slips through unmapped degrades to a
// blank flag instead of a missing background.
export const INTERFACE_FLAG_COUNTRY_CODES = ["gb", "tr", "xx"];

export const FLAG_COUNTRY_CODES: string[] = [
  ...new Set([
    ...Object.values(LANGUAGE_FLAG_COUNTRY_CODES),
    ...Object.values(COUNTRY_NAME_FLAG_CODES),
    ...INTERFACE_FLAG_COUNTRY_CODES,
  ]),
].sort();
