import { base64UrlDecode, base64UrlEncode } from "./core";

/**
 * Web Push without a payload.
 *
 * A push carries nothing: it only wakes the device's service worker, which
 * then asks this service for the newest alert with its own viewer token. That
 * leaves out the whole of payload encryption (RFC 8291), and it means the push
 * services in between never see the text of an alert at all. All a push needs
 * is a VAPID token (RFC 8292) saying which application sent it.
 */

export interface PushSubscriptionRecord {
  endpoint: string;
}

export interface VapidKeys {
  /** The P-256 private key as a JWK, as generated by scripts/vapid.mjs. */
  privateJwk: JsonWebKey;
  /** The uncompressed public point, base64url, as browsers want it. */
  publicKey: string;
  /** Who operates this sender, for push services to contact. */
  subject: string;
}

const encoder = new TextEncoder();

/** A VAPID JWT for one push service origin, signed ES256. */
export async function vapidToken(
  audience: string,
  keys: VapidKeys,
  now: number,
): Promise<string> {
  const header = base64UrlEncode(
    encoder.encode(JSON.stringify({ typ: "JWT", alg: "ES256" })),
  );
  const claims = base64UrlEncode(
    encoder.encode(
      JSON.stringify({
        aud: audience,
        // Push services refuse anything longer than a day.
        exp: Math.floor(now / 1000) + 12 * 60 * 60,
        sub: keys.subject,
      }),
    ),
  );
  const key = await crypto.subtle.importKey(
    "jwk",
    keys.privateJwk,
    { name: "ECDSA", namedCurve: "P-256" },
    false,
    ["sign"],
  );
  // WebCrypto already produces the raw r||s form JWS wants.
  const signature = await crypto.subtle.sign(
    { name: "ECDSA", hash: "SHA-256" },
    key,
    encoder.encode(`${header}.${claims}`),
  );
  return `${header}.${claims}.${base64UrlEncode(new Uint8Array(signature))}`;
}

export type PushOutcome = "sent" | "gone" | "failed";

/** Sends one empty push; "gone" means the subscription should be forgotten. */
export async function sendEmptyPush(
  subscription: PushSubscriptionRecord,
  keys: VapidKeys,
  now: number,
  fetchImpl: typeof fetch = fetch,
): Promise<PushOutcome> {
  const endpoint = new URL(subscription.endpoint);
  const token = await vapidToken(endpoint.origin, keys, now);
  try {
    const response = await fetchImpl(subscription.endpoint, {
      method: "POST",
      headers: {
        TTL: String(24 * 60 * 60),
        Urgency: "high",
        Authorization: `vapid t=${token}, k=${keys.publicKey}`,
        "Content-Length": "0",
      },
    });
    if (response.status === 404 || response.status === 410) return "gone";
    return response.ok ? "sent" : "failed";
  } catch {
    return "failed";
  }
}

/** Whether a public key string is a well-formed uncompressed P-256 point. */
export function isPublicKey(value: string): boolean {
  try {
    const bytes = base64UrlDecode(value);
    return bytes.length === 65 && bytes[0] === 4;
  } catch {
    return false;
  }
}
