/**
 * What publication actually proves about the copy it just made.
 *
 * ## The policy, stated exactly
 *
 * Every published file is compared against the verified scratch original by
 * `replicasMatch`, which is size plus a SHA-256 over sampled windows:
 *
 *  - **Size** is compared first and is exact. Any difference at all — a
 *    truncated destination, a short write, a longer file — fails immediately
 *    and without reading a byte.
 *  - **Files of 3 MiB or less** are hashed *in full*: the sampling window is
 *    1 MiB and a file of three windows or fewer has every window read. For
 *    these, any single altered byte is caught.
 *  - **Files larger than 3 MiB** are hashed over exactly three 1 MiB windows —
 *    the first, the middle and the last — with the file's size mixed into the
 *    digest. Verification I/O per file is therefore capped at 3 MiB a side
 *    regardless of whether the file is 4 MiB or 400 GB.
 *  - **Playlist byte ranges** are re-parsed on the destination and every range
 *    must end inside the media file that was copied, so a playlist and its
 *    media cannot disagree about how long the media is.
 *  - **The expected file set** is taken from the package manifest: every video,
 *    audio and subtitle rendition's media and playlist, plus the master
 *    playlist, the manifest and the build record, must exist and be non-empty
 *    before anything is renamed into place — and after the swap every file the
 *    manifest names is re-checked against its recorded size.
 *
 * ## What this deliberately does not do
 *
 * It does not hash whole files. For a 400 GB package that would mean reading
 * 800 GB — the package twice, once from each disk — roughly doubling
 * publication time to re-establish something the copy already had in memory.
 * The cost is a bounded blind spot, pinned by the last test in this file: a
 * same-size alteration in a large file that falls outside all three sampled
 * windows is not detected by this check. That is a deliberate trade and the
 * test exists so that it stays a deliberate one.
 */

import { createHash, randomBytes } from "node:crypto";
import {
  mkdtemp,
  open,
  readFile,
  rm,
  stat,
  truncate,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { copyFileResumable } from "./publishTitle";

const MIB = 1024 * 1024;
const roots: string[] = [];

afterEach(async () => {
  await Promise.all(
    roots.splice(0).map((root) => rm(root, { recursive: true, force: true })),
  );
});

async function fixture(): Promise<string> {
  const root = await mkdtemp(path.join(tmpdir(), "seyirlik-verify-"));
  roots.push(root);
  return root;
}

/**
 * Incompressible, non-uniform content built by tiling one random block.
 *
 * Random rather than a run of zeroes because a uniform file cannot distinguish
 * "these windows match" from "every window is the same"; tiled rather than
 * generated byte by byte because these files run to double-digit megabytes and
 * a per-byte loop in JavaScript takes longer than the test timeout.
 */
function pattern(size: number): Buffer {
  const block = randomBytes(Math.min(size, MIB));
  const buffer = Buffer.allocUnsafe(size);
  for (let offset = 0; offset < size; offset += block.length) {
    block.copy(buffer, offset, 0, Math.min(block.length, size - offset));
    // Distinguish the tiles, so two windows are never accidentally identical.
    buffer[offset] = (offset / block.length) & 0xff;
  }
  return buffer;
}

/**
 * A whole-file digest, used for the assertions themselves.
 *
 * Deliberately not `expect(buffer).toEqual(buffer)`: comparing two ten-megabyte
 * Buffers makes the matcher build a diff of ten million elements and exhausts
 * the worker's heap. Comparing one hex string to another says the same thing.
 */
async function digestOf(filePath: string): Promise<string> {
  return createHash("sha256")
    .update(await readFile(filePath))
    .digest("hex");
}

/** Flips one byte in place at an absolute offset, preserving the file size. */
async function flipByteAt(filePath: string, offset: number): Promise<void> {
  const handle = await open(filePath, "r+");
  try {
    const one = Buffer.allocUnsafe(1);
    await handle.read(one, 0, 1, offset);
    one[0] = one[0]! ^ 0xff;
    await handle.write(one, 0, 1, offset);
  } finally {
    await handle.close();
  }
}

/**
 * Publishes `source` to `destination` and says whether the result was accepted
 * as already correct, repaired, or refused.
 *
 * `copyFileResumable` has three outcomes and a test that only asked "did it
 * throw" would miss the interesting one: a destination it detects as wrong and
 * silently rewrites is still a detection, and a destination it accepts without
 * rewriting is the case that matters for corruption.
 */
async function publishAgain(
  source: string,
  destination: string,
): Promise<"accepted-unchanged" | "rewritten" | "refused"> {
  const before = await stat(destination).catch(() => null);
  const beforeDigest = before ? await digestOf(destination) : null;
  try {
    await copyFileResumable(source, destination);
  } catch {
    return "refused";
  }
  return (await digestOf(destination)) === beforeDigest
    ? "accepted-unchanged"
    : "rewritten";
}

describe("verifying a published copy", () => {
  it("accepts a destination that is byte-identical without rewriting it", async () => {
    const root = await fixture();
    const source = path.join(root, "source.m4s");
    const destination = path.join(root, "destination.m4s");
    const bytes = pattern(5 * MIB);
    await writeFile(source, bytes);
    await writeFile(destination, bytes);

    // The cheap path: nothing is copied and nothing is disturbed.
    expect(await publishAgain(source, destination)).toBe("accepted-unchanged");
  }, 60_000);

  it("detects a truncated destination", async () => {
    const root = await fixture();
    const source = path.join(root, "source.m4s");
    const destination = path.join(root, "destination.m4s");
    const bytes = pattern(5 * MIB);
    await writeFile(source, bytes);
    await writeFile(destination, bytes);
    // The classic half-written file: a publication that died mid-copy.
    await truncate(destination, 3 * MIB);

    expect(await publishAgain(source, destination)).toBe("rewritten");
    expect((await stat(destination)).size).toBe(5 * MIB);
    expect(await digestOf(destination)).toBe(await digestOf(source));
  }, 60_000);

  it("detects a destination that is longer than its source", async () => {
    const root = await fixture();
    const source = path.join(root, "source.m4s");
    const destination = path.join(root, "destination.m4s");
    await writeFile(source, pattern(4 * MIB));
    await writeFile(destination, pattern(6 * MIB));

    expect(await publishAgain(source, destination)).toBe("rewritten");
    expect((await stat(destination)).size).toBe(4 * MIB);
    expect(await digestOf(destination)).toBe(await digestOf(source));
  }, 60_000);

  it.each([
    ["the first sampled window", 4096],
    ["the middle sampled window", Math.floor((10 * MIB) / 2)],
    ["the final sampled window", 10 * MIB - 4096],
  ])(
    "detects same-size corruption in %s",
    async (_label, offset) => {
      const root = await fixture();
      const source = path.join(root, "source.m4s");
      const destination = path.join(root, "destination.m4s");
      const bytes = pattern(10 * MIB);
      await writeFile(source, bytes);
      await writeFile(destination, bytes);
      await flipByteAt(destination, offset);

      /*
       * Either outcome proves detection: the corruption is repaired in place, or
       * the copy refuses and discards it. What must never happen is the
       * destination being accepted as it stands.
       */
      const outcome = await publishAgain(source, destination);
      expect(outcome).not.toBe("accepted-unchanged");

      /*
       * And whichever happened, the job can still make progress: a retry either
       * finds a correct file or finds none, never a same-size wrong one that it
       * would keep re-verifying and re-rejecting for ever.
       */
      await copyFileResumable(source, destination);
      expect(await digestOf(destination)).toBe(
        createHash("sha256").update(bytes).digest("hex"),
      );
    },
    60_000,
  );

  it("detects a different file of exactly the same size", async () => {
    const root = await fixture();
    const source = path.join(root, "source.m4s");
    const destination = path.join(root, "destination.m4s");
    await writeFile(source, pattern(8 * MIB));
    // The wrong rendition published under the right name: same size, different
    // content throughout. Size alone would wave this through.
    await writeFile(destination, pattern(8 * MIB));

    expect(await publishAgain(source, destination)).not.toBe(
      "accepted-unchanged",
    );
    expect(await digestOf(destination)).toBe(await digestOf(source));
  }, 60_000);

  it("catches a single flipped byte anywhere in a small file", async () => {
    const root = await fixture();
    const bytes = pattern(2 * MIB);
    /*
     * Under the 3 MiB threshold every window is read, so the guarantee for
     * small files is total. Playlists, manifests and build records are all far
     * below it, which is why the package's own descriptions are covered
     * exactly rather than approximately.
     */
    for (const offset of [0, MIB + 12345, 2 * MIB - 1]) {
      const source = path.join(root, `small-${offset}.m4s`);
      const destination = path.join(root, `small-dest-${offset}.m4s`);
      await writeFile(source, bytes);
      await writeFile(destination, bytes);
      await flipByteAt(destination, offset);

      expect(await publishAgain(source, destination)).not.toBe(
        "accepted-unchanged",
      );
      // The retry that follows a rejection completes rather than repeating it.
      await copyFileResumable(source, destination);
      expect(await digestOf(destination)).toBe(
        createHash("sha256").update(bytes).digest("hex"),
      );
    }
  }, 60_000);

  it("resumes a partial destination without recopying its good prefix", async () => {
    const root = await fixture();
    const source = path.join(root, "source.m4s");
    const destination = path.join(root, "destination.m4s");
    const bytes = pattern(6 * MIB);
    await writeFile(source, bytes);
    // Two thirds already copied, correctly, by a publication that was cut off.
    await writeFile(destination, bytes.subarray(0, 4 * MIB));

    let firstReported = -1;
    await copyFileResumable(source, destination, {
      onProgress: (completed) => {
        if (firstReported < 0) firstReported = completed;
      },
    });

    // Progress starts from what was already there rather than from zero.
    expect(firstReported).toBe(4 * MIB);
    expect(await digestOf(destination)).toBe(
      createHash("sha256").update(bytes).digest("hex"),
    );
  }, 60_000);

  it("discards a partial destination whose tail does not match", async () => {
    const root = await fixture();
    const source = path.join(root, "source.m4s");
    const destination = path.join(root, "destination.m4s");
    const bytes = pattern(6 * MIB);
    await writeFile(source, bytes);
    const partial = Buffer.from(bytes.subarray(0, 4 * MIB));
    partial[4 * MIB - 10] = partial[4 * MIB - 10]! ^ 0xff;
    await writeFile(destination, partial);

    let firstReported = -1;
    await copyFileResumable(source, destination, {
      onProgress: (completed) => {
        if (firstReported < 0) firstReported = completed;
      },
    });

    // The suffix could not be trusted, so the file is rebuilt from the start.
    expect(firstReported).toBe(0);
    expect(await digestOf(destination)).toBe(
      createHash("sha256").update(bytes).digest("hex"),
    );
  });
});

describe("the documented limit of sampled verification", () => {
  it("does not detect a same-size change outside the sampled windows", async () => {
    const root = await fixture();
    const source = path.join(root, "source.m4s");
    const destination = path.join(root, "destination.m4s");
    const size = 12 * MIB;
    const bytes = pattern(size);
    await writeFile(source, bytes);
    await writeFile(destination, bytes);

    /*
     * Between the first window (0–1 MiB) and the middle one (5.5–6.5 MiB), so
     * no sampled byte changes and the size does not move.
     */
    const blindOffset = 3 * MIB;
    await flipByteAt(destination, blindOffset);

    /*
     * This is the cost of not reading 400 GB twice, and it is recorded here
     * rather than left to be discovered.
     *
     * It is bounded in practice by what the rest of the pipeline already
     * proves: the bytes came from a package that passed deep validation on
     * scratch, they were written by a copy that had just read them, and the
     * destination's playlists and sizes are re-checked against the manifest
     * afterwards. What is *not* proven is the interior of a large media file
     * against silent corruption on the destination device.
     *
     * If this assertion ever fails because the policy was strengthened, delete
     * it — do not weaken the new policy to keep it passing.
     */
    expect(await publishAgain(source, destination)).toBe("accepted-unchanged");
  });
});
