import { randomUUID } from "node:crypto";
import path from "node:path";
import { TITLE_TRICKPLAY_DIRECTORY } from "../../../renditions/adaptive/layout";

/**
 * Where a title's trickplay sheets are, and how the three populations that
 * carry the word "trickplay" are told apart.
 *
 * There is exactly one answer to "where do this title's sheets live", and it is
 * computed here from the title root and nowhere else. Generation, serving,
 * deletion, regeneration, migration and validation all resolve through these
 * functions, so the writer and the reader cannot drift apart the way they did
 * when the address was a UUID recorded in a column.
 *
 * The three populations, which must never be confused:
 *
 * - `<titleRoot>/trickplay/` — live, managed, generated by this server. The
 *   only one with any runtime authority.
 * - `<something>.trickplay/` — external, Jellyfin-era, historical. Present
 *   inside the media volume today, archived out of it by the maintenance
 *   command, and never live at any point in its life.
 * - `<generated storage>/trickplay/<uuid>/` — this server's own previous
 *   layout, being migrated into the first form and then removed.
 */

/** The directory a title's live sheets occupy. */
export function trickplayDirectoryFor(titleRoot: string): string {
  return path.join(titleRoot, TITLE_TRICKPLAY_DIRECTORY);
}

/**
 * Sheets are numbered from zero because every reader of them counts from zero:
 * `spritePath`, `tilesInSprite`, and the seek bar's own tile arithmetic.
 */
export function spriteFileName(spriteIndex: number): string {
  return `sprite_${spriteIndex}.jpg`;
}

export function spritePathIn(directory: string, spriteIndex: number): string {
  return path.join(directory, spriteFileName(spriteIndex));
}

/**
 * The prefix of a directory a generation stages into before it is swapped in.
 *
 * It begins with a dot for one reason beyond tidiness: the scanner ignores
 * every entry whose name starts with `.`, so a generation that is still running
 * — or one interrupted and left behind — can never be walked into as if it held
 * media. See `isIgnoredEntry` in the scanner's name parser.
 */
export const TRICKPLAY_STAGING_PREFIX = ".trickplay-publish";

/** Where a retired live directory waits while its replacement is swapped in. */
export const TRICKPLAY_RETIRED_SUFFIX = ".retired";

export function trickplayStagingDirectory(
  titleRoot: string,
  id: string = randomUUID(),
): string {
  return path.join(titleRoot, `${TRICKPLAY_STAGING_PREFIX}-${id}`);
}

export function isTrickplayStagingDirectory(name: string): boolean {
  return name.startsWith(`${TRICKPLAY_STAGING_PREFIX}-`);
}

/**
 * An entry the filesystem put there, which nothing in this server wrote.
 *
 * This library is on exFAT, which has nowhere to keep an extended attribute.
 * macOS tags every file a process creates with `com.apple.provenance`, and on
 * such a volume that tag is materialised as an AppleDouble sidecar: writing
 * `sprite_0.jpg` silently produces a 4 KiB `._sprite_0.jpg` beside it, and
 * creating a directory produces a `._` twin of the directory too. Copying a
 * file reproduces the pair at the far end, which is why a verified copy still
 * compares equal.
 *
 * Two places have to know the difference between a file the server wrote and
 * one the operating system did: the validator, which would otherwise read a
 * decorated directory as a corrupted one, and the migration's emptiness check,
 * which would otherwise never see the old root as empty.
 *
 * Deliberately an exact two-name list rather than "ignore anything unexpected".
 * Both callers exist to notice things that should not be there, and they go on
 * noticing everything except the names a Mac writes by itself.
 */
export function isFilesystemSidecar(name: string): boolean {
  return name.startsWith("._") || name === ".DS_Store";
}

/**
 * Whether a directory name is an old external trickplay folder.
 *
 * This is the predicate destructive work is allowed to use, and it is written
 * as an exact suffix test rather than a substring search for a reason: a
 * `name.includes("trickplay")` would match the managed `trickplay` directory,
 * and the tool that uses this predicate deletes what it matches.
 *
 * `.trickplay` alone does not qualify either — a name that is nothing but the
 * suffix is a hidden directory, not `<title>.trickplay`.
 */
export function isLegacyExternalTrickplayDirectory(name: string): boolean {
  const LEGACY_SUFFIX = ".trickplay";
  if (name === TITLE_TRICKPLAY_DIRECTORY) return false;
  if (!name.endsWith(LEGACY_SUFFIX)) return false;
  return name.length > LEGACY_SUFFIX.length;
}

/**
 * Whether `candidate` resolves inside `root`.
 *
 * Resolution happens before the comparison, never after: checking a path that
 * still contains `..` tells you what the string looks like rather than where it
 * goes. The separator is appended so `/media-old` is not read as being inside
 * `/media`.
 */
export function isInsideDirectory(root: string, candidate: string): boolean {
  const resolvedRoot = path.resolve(root);
  const resolved = path.resolve(candidate);
  if (resolved === resolvedRoot) return true;
  return resolved.startsWith(
    resolvedRoot.endsWith(path.sep)
      ? resolvedRoot
      : `${resolvedRoot}${path.sep}`,
  );
}
